#!/bin/bash

#
# Helper script to call tmap index
#
TMP_CUR_DIR=`dirname $0`
TMP_TABSAT_SCRIPT="$TMP_CUR_DIR/../../tabsat"
TMP_ABS_TABSAT_SCRIPT=`readlink -f $TMP_TABSAT_SCRIPT`
BASE_DIR=`dirname $TMP_ABS_TABSAT_SCRIPT`
TOOLS="${BASE_DIR}/tools"

echo "TOOLS DIR: ${TOOLS}"

${TOOLS}/iontorrent/tmap index "$@"

